### ISSUE TITLE
Bug in provider time when updating from triggers

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/terraform-provider-time#109]
Terraform 1.2.5
terraform-provider-time 0.7.2
OS: darwin arm64 (m1)

Was getting this error when using time_sleep with triggers. I am using time_sleep to enforce a wait period after I set a policy or role, before continuing to use that role/policy in other parts of the terraform run. 

Error:

```
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.foo.time_sleep.ready
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/time" produced an invalid new value for
│ .triggers["assume_role_policy"]: was cty.StringVal("{\n  \"Version\":
│ \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\":
│ \"AllowAssumingViaSAMLFederationByAzureIDP\",\n      \"Effect\":
│ \"Allow\",\n      \"Action\": \"sts:AssumeRoleWithSAML\",\n
│ \"Principal\": {\n        \"Federated\":
│ \"arn:aws:iam::XXXXXXXXXXXX:saml-provider/azure\"\n
│ },\n      \"Condition\": {\n        \"StringEquals\": {\n
│ \"SAML:aud\": \"https://signin.aws.amazon.com/saml\"\n        }\n      }\n
│ }\n  ]\n}"), but now
│ cty.StringVal("{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"AllowAssumingViaSAMLFederationByAzureIDP\",\"Effect\":\"Allow\",\"Principal\":{\"Federated\":\"arn:aws:iam::XXXXXXXXXXXX:saml-provider/azure\"},\"Action\":\"sts:AssumeRoleWithSAML\",\"Condition\":{\"StringEquals\":{\"SAML:aud\":\"https://signin.aws.amazon.com/saml\"}}}]}").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

Here is the code:

```
resource "time_sleep" "ready" {
  triggers = {
    name               = aws_iam_role.this.name
    assume_role_policy = aws_iam_role.this.assume_role_policy
    #    TODO: 
    #    inline_policies      = join(",", aws_iam_role_policy.this.*.policy)
    #    managed_policies     = join(",", aws_iam_role_policy_attachment.this.*.policy_arn)
    permissions_boundary = aws_iam_role.this.permissions_boundary
  }
  create_duration = "10s"
  depends_on = [
    aws_iam_role.this
  ]
}
```

Here was the plan for the offending resource:

```
  # module.foo.time_sleep.ready will be created
  + resource "time_sleep" "ready" {
      + create_duration = "10s"
      + id              = (known after apply)
      + triggers        = {
          + "assume_role_policy" = jsonencode(
                {
                  + Statement = [
                      + {
                          + Action    = "sts:AssumeRoleWithSAML"
                          + Condition = {
                              + StringEquals = {
                                  + "SAML:aud" = "https://signin.aws.amazon.com/saml"
                                }
                            }
                          + Effect    = "Allow"
                          + Principal = {
                              + Federated = "arn:aws:iam::XXXXXXXXXXXX:saml-provider/azure"
                            }
                          + Sid       = "AllowAssumingViaSAMLFederationByAzureIDP"
                        },
                    ]
                  + Version   = "2012-10-17"
                }
            )
          + "name"               = "my-role-name"
        }
    }
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* time_sleep

**Comment by bflad** [comment]
Hi @gtmtech 👋

As mentioned in the duplicate Terraform core issue, this error is actually caused by the AWS provider and can be tracked here: https://github.com/hashicorp/terraform-provider-aws/issues/23965

Terraform generally requires providers to be consistent with attribute values between a configuration, plan, and state. Sometimes a provider may be able to handle and ignore syntactical differences with certain values, such as JSON strings, but it is up to the original provider handling that value to follow Terraform's consistency rules and requirements. If you take a peek at Terraform's warning logs, e.g. `TF_LOG=WARN terraform apply`, there should be an entry in those logs referencing that particular value being inconsistent from the AWS provider when you see this time provider error. Providers implemented with terraform-plugin-sdk have special rules in Terraform to demote either unavoidable errors or backwards compatibility issues to warning logs. The time provider is referenced in this error diagnostic is simply as "passthrough" of this value, but because AWS provider warning log doesn't stop the apply from continuing, downstream configuration references to problematic values in Terraform do not know about the upstream resource's demoted error so the error will show up outside the original location.

I know this is fairly confusing, but hope this helps clarify things some. There are efforts underway to migrate providers away from terraform-plugin-sdk and its special handling onto terraform-plugin-framework, but this is not an easy task and will be provider-dependent which resources are prioritized first.

**Comment by bflad** [comment]
By the way in this particular configuration setup, I'm not seeing any sort of "version" attribute on the `aws_iam_role` resource, but a potential workaround may be to use `jsondecode(aws_iam_role.this.assume_role_policy)` to remove the JSON syntactical differences from causing the error via the `time_sleep` resource `triggers` attribute.
