### ISSUE TITLE
Cut a new release of this provider

### ISSUE THREAD

**Issue by aochsner** [hashicorp/terraform-provider-time#327]
### Terraform CLI and Provider Versions

1.8.4 & 0.11.1

### Use Cases or Problem Statement

https://discuss.hashicorp.com/t/cut-a-new-hashicorp-time-provider-release/67314

### Proposal

I'm not sure if this is the right place but also posted in the discussion forums.

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @aochsner 👋 (and other future readers),

Thanks for that additional context. I'm not on the HashiCorp security team, but I wanted to give some additional information about this particular scanner report. For official security disclosures/responses from the security team, please refer to https://www.hashicorp.com/trust/security.

The `github.com/go-git/go-git/v5` dependency in this provider codebase is not in the "production" provider server codepath, but is pulled in due some underlying capabilities of the provider testing library so that it can potentially build Terraform from a specific Git reference when a specific environment variable is passed while running the provider testing.

```console
$ ❯ go mod why -m 'github.com/go-git/go-git/v5'
# github.com/go-git/go-git/v5
github.com/hashicorp/terraform-provider-time/internal/provider
github.com/hashicorp/terraform-provider-time/internal/provider.test
github.com/hashicorp/terraform-plugin-testing/helper/resource
github.com/hashicorp/terraform-exec/tfexec
github.com/hashicorp/terraform-exec/tfexec.test
github.com/hashicorp/terraform-exec/tfexec/internal/testutil
github.com/hashicorp/hc-install/build
github.com/go-git/go-git/v5
```

Unfortunately a lot of security scanners cannot have code-level context on why or how a dependency is being used or not, but the reality is that many compliance officers need to rely these reports as given. So for anyone who may see references to this dependency or CVE number in relation to this provider codebase (and potentially others in the provider ecosystem), I just wanted to help alleviate any sort of urgency to upgrade. I have created https://github.com/hashicorp/terraform-plugin-testing/issues/347 in the provider testing Go module to consider removing the functionality that causes this dependency to appear in provider codebases to reduce security scanning reports like these.

As @austinvalle mentioned though, we can/will cut a fresh provider release to help remove this particular scanner report for now. 👍
