### ISSUE TITLE
Github Release is outdated / misleading

### ISSUE THREAD

**Issue by krsche** [hashicorp/terraform-provider-time#70]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
This github repo -> Releases page

### Expected Behavior

Github repo `Releases` page lists correct latest version of library (`0.7.2`), or no release at all so the viewer has to check the available tags manually.

### Actual Behavior

The Releases page shows version `0.3.0` to be the latest available release of this library, which is not true. The release isn't even available anymore.

### Steps to Reproduce

Go to https://github.com/hashicorp/terraform-provider-time/releases

**Comment by bflad** [comment]
Hi @krsche 👋  Thank you for raising this.

I have backfilled the missing releases by adding a GitHub Release on each tag that was missing one. This codebase is using a new release process since the last time a release was made, but future releases should properly create GitHub Releases that are associated with the release tag.

Please note that the canonical source for HashiCorp maintained Terraform Providers is https://registry.terraform.io/ with release assets stored at https://releases.hashicorp.com/. Any GitHub Releases are provided without release assets and as best effort (v0.3.0 was created before the project was transferred to HashiCorp).
